name = "RxInferServer"
uuid = "e92bdd6b-15d6-410c-ab97-e133e2594943"
authors = ["Lazy Dynamics <info@lazydynamics.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
RxInferServerOpenAPI = "476dbcea-416d-4115-b70c-6e4041cc1de4"

[sources]
RxInferServerOpenAPI = {path = "openapi/server"}

[compat]
Dates = "1.11.0"
HTTP = "1.10.15"
JSON3 = "1.14"
Preferences = "1.4"
Revise = "3.7.2"
RxInfer = "3.10"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "ReTestItems", "HTTP", "Hwloc", "Distributions", "StableRNGs"]
