[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
RxInferServer = "e92bdd6b-15d6-410c-ab97-e133e2594943"
RxInferClientOpenAPI = "8b1d2e5c-3735-4918-bca0-1c0cc8ef920a"

[sources]
RxInferClientOpenAPI = {path = "../openapi/client"}
